/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1/userguide/multi_project_builds.html
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("logback", "1.4.7")

            library("logback-classic", "ch.qos.logback", "logback-classic")
                .versionRef("logback")
        }
    }
}


rootProject.name = "java-netrc"
include("lib")
project(":lib").name = "netrc-parser"
